config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  get "dashboard", to: 'dashboard#show', as: :dashboard, constraints: Routes::LoggedInConstraint.new

  concern :calendar do
    get 'week/:week', to: 'entries#index', as: :week
    get 'week/:week/day/:day', to: 'entries#index', as: :week_day
  end

  resources :schedules, concerns: :calendar do
    resources :entries, path: 'workouts'
  end

  resources :training_plans, concerns: :calendar, path: 'training-plans' do
    resources :entries, path: 'workouts'
  end

  resources :events

  resources :tags

  get 'accounts/start', to: redirect('start')

  devise_for :users,
    skip: [:sessions],
    path: 'accounts',
    path_names: { sign_up: 'start' },
    controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  as :user do
    get 'resume' => 'devise/sessions#new', :as => :new_user_session
    post 'resume' => 'devise/sessions#create', :as => :user_session
    match 'pause' => 'devise/sessions#destroy', :as => :destroy_user_session,
      :via => Devise.mappings[:user].sign_out_via

    get 'start' => 'devise/registrations#new', :as => :sign_up
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def show
    @dashboard = DashboardPresenter.new(current_user)
  end

  class DashboardPresenter
    def initialize(user)
      @user = user
    end

    def entries
      @entries ||= Entry.joins(:schedule).merge(@user.schedules)
    end

    def entries_today
      entries.today
    end

    def entries_tomorrow
      entries.tomorrow
    end
  end
end

app/views/dashboard/show.html.erb
<% extra_main_classes 'dashboard', 'index-page' %>
<h2 class="index-page--title">Welcome</h2>

<div>
  <h3>Today</h3>
  <div class="entries today">
    <%= render @dashboard.entries_today %>
  </div>
  <h3>Tomorrow</h3>
  <div class="entries tomorrow">
    <%= render @dashboard.entries_tomorrow %>
  </div>
</div>

<ul class="large-block-grid-1">
  <% current_user.schedules.active.each do |schedule| %>
    <li>
      <h3><%= link_to schedule.title, schedule %></h3>
      <p>Race date: <%= schedule.peaks_on.to_s(:long) %></p>
    </li>
  <% end %>
</ul>

<hr />
<%= link_to "Start training", new_schedule_path, class: "small button success round" %>
<%= link_to "Create new training plan", new_training_plan_path, class: "small button round" %>