config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  get "dashboard", to: 'dashboard#show', as: :dashboard, constraints: Routes::LoggedInConstraint.new

  concern :calendar do
    get 'week/:week', to: 'entries#index', as: :week
    get 'week/:week/day/:day', to: 'entries#index', as: :week_day
  end

  resources :schedules, concerns: :calendar do
    resources :entries, path: 'workouts'
  end

  resources :training_plans, concerns: :calendar, path: 'training-plans' do
    resources :entries, path: 'workouts'
  end

  resources :events

  resources :tags

  get 'accounts/start', to: redirect('start')

  devise_for :users,
    skip: [:sessions],
    path: 'accounts',
    path_names: { sign_up: 'start' },
    controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  as :user do
    get 'resume' => 'devise/sessions#new', :as => :new_user_session
    post 'resume' => 'devise/sessions#create', :as => :user_session
    match 'pause' => 'devise/sessions#destroy', :as => :destroy_user_session,
      :via => Devise.mappings[:user].sign_out_via

    get 'start' => 'devise/registrations#new', :as => :sign_up
  end

end

app/models/entry.rb
# == Schema Information
#
# Table name: entries
#
#  id               :integer          not null, primary key
#  summary          :string(255)
#  notes            :text
#  day              :integer
#  week             :integer
#  created_at       :datetime
#  updated_at       :datetime
#  distance         :string           default("0 m")
#  duration         :string           default("0 s")
#  occurs_on        :date
#  schedulable_id   :integer
#  schedulable_type :string
#

class Entry < ActiveRecord::Base
  include Concerns::Categorizable

  belongs_to :schedulable, polymorphic: true, inverse_of: :entries

  belongs_to :schedule, -> { joins(:entries).merge(Entry.for_schedules) }, foreign_key: :schedulable_id
  belongs_to :training_plan, -> { joins(:entries).merge(Entry.for_training_plans) }, foreign_key: :schedulable_id

  scope :today, -> { where(occurs_on: Time.zone.today.to_date ) }
  scope :tomorrow, -> { where(occurs_on: Time.zone.tomorrow.to_date ) }
  scope :for_schedules, -> { where(schedulable_type: 'Schedule') }
  scope :for_training_plans, -> { where(schedulable_type: 'TrainingPlan') }

  enum day: %w[ Monday Tuesday Wednesday Thursday Friday Saturday Sunday ]

  validates :week, numericality: { greater_than: 0, less_than_or_equal_to: :total_weeks }

  # validates :duration, duration_unit: true
  # validates :distance, distance_unit: true

  has_one_category :period
  has_one_category :discipline
  has_one_category :zone
  has_one_category :mode
  has_many_categories :abilities
  has_many_categories :strength_abilities

  def combined_ability_names
    ability_names + strength_ability_names
  end

  def secondary_category_names
    combined_ability_names + [zone_name, mode_name].reject(&:blank?)
  end

  def training_week
    @training_week ||= TrainingWeek.new(number: week, period: schedulable.period(week))
  end

  def self.day_names
    days.keys
  end

  def total_weeks
    schedulable.total_weeks
  end

  def title
    [display_week, summary, display_day].reject(&:blank?).join(' ')
  end

  def display_day
    day
  end

  def display_week
    training_week.title
  end

  def distance=(given_distance)
    self.distance_unit = given_distance
    super
  end

  def distance_unit=(given_distance)
    @distance_unit = to_unit(given_distance)
  end

  def distance_unit
    @distance_unit || to_unit(self.distance)
  end

  def distance_for_unit(unit_name = 'm')
    distance_unit.convert_to(unit_name)
  end
  alias :distance_in :distance_for_unit

  def distance_for_discipline
    distance_for_unit discipline_distance_unit
  end

  def duration=(given_duration)
    self.duration_unit = given_duration
    super
  end

  def duration_unit=(given_duration)
    @duration_unit = to_unit(given_duration)
  end

  def duration_unit
    to_unit(self.duration)
  end

  def duration_for_unit(unit_name = 's')
    duration_unit.convert_to(unit_name)
  end
  alias :duration_in :duration_for_unit

  def date_relative_to(date)
    return NullDate.new unless week.present? && day.present?
    date.to_date + week_index.weeks + day_index.days
  end

  def week_index
    week.presence && (week - 1)
  end

  def day_index
    day.presence && Entry.days[day]
  end

  def to_unit(value)
    return nil if value.blank?

    Unit(extract_last_unit_value(value))
  end

  def copyable_attributes
    copyable_attribute_names.inject({}) { |attrs, name| attrs[name] = send(name); attrs }
  end

  private

  def extract_last_unit_value(value)
    value.split(%r{\s?-\s?}).last.strip
  end

  def copyable_attribute_names
    %w[
      summary
      notes
      week
      day
      discipline_name
      mode_name
      zone_name
      period_name
      distance
      duration
      ability_names
      strength_ability_names
    ]
  end

  def discipline_distance_unit
    if discipline_tagging
      discipline_tagging.distance_unit
    else
      'mi'
    end
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  # scoped to training_plan, schedule

  respond_to :html

  def index
    @entries = scope
    @title = @entry_scope.title
    if index_params.any?
      @entries = @entries.where(index_params)
      @week    = @entry_scope.week_number(index_params[:week])
      @title   += ": #{@week.title}"
    end
    @entries = @entries.order(week: :asc, day: :asc)
  end

  def show
    @entry = scope.find(params[:id])
  end

  def new
    @entry = scope.build(index_params)
  end

  def create
    @entry = scope.build(entry_params)

    if @entry.save
      redirect_to [@training_plan, @entry], notice: "Success"
    else
      render :new
    end
  end

  def edit
    @entry = scope.find(params[:id])
  end

  def update
    @entry = scope.find(params[:id])
    @entry.attributes = entry_params

    if @entry.save
      redirect_to [@training_plan, @entry], notice: "Success"
    else
      render :edit
    end
  end

  private

  def scope
    @entry_scope = entry_scope
    @entry_scope.entries
  end

  def entry_scope
    case
    when params[:training_plan_id]
      @training_plan = TrainingPlan.find(params[:training_plan_id])
    when params[:schedule_id]
      @schedule = Schedule.find(params[:schedule_id])
    else
      raise ActiveRecord::RecordNotFound
    end
  end

  def entry_params
    params.require(:entry).permit(
      :summary,
      :notes,
      :week,
      :day,
      :discipline_name,
      :zone_name,
      :period_name,
      :distance,
      :duration,
      ability_names: [],
      strength_ability_names: []
    )
  end

  def index_params
    params.permit(:schedule_id, :training_plan_id, :week, :day).slice(:week, :day)
  end
  helper_method :index_params

end

app/helpers/entries_helper.rb
module EntriesHelper

end

app/views/entries/_categories.html.erb
<%= render_label entry.discipline_name, 'success' %>
<%= render_label entry.period_name %>
<%= render_labels entry.secondary_category_names, 'secondary' %>

app/views/entries/_entry.html.erb
<% week ||= entry.training_week %>
<section id="<%= dom_id(entry) %>" class="<%= dom_class(entry) %> row">
  <div class="columns large-6 small-6">
    <% if week.has_dates? %>
      <%= l week.day_date(entry.day), format: :short %>
    <% else %>
      <%= entry.display_day %>
    <% end %>
    <p><i><%= link_to entry.summary, [entry.schedulable, entry]%></i></p>
    <p data-role="notes">
      Notes:<br/>
      <%= entry.duration %><br/>
      <%= entry.notes %>
    </p>
  </div>
  <div class="columns large-6 small-6">
    <p data-role="requirements"><%= render 'entries/requirements', entry: entry %></p>
    <p date-role="categories"><%= render 'entries/categories', entry: entry %> </p>
  </div>
</section>

app/views/entries/_form.html.erb
<h1>Plan a Workout</h1>

<p><%= @entry_scope.class.name.humanize %>: <%= @entry_scope.title %></p>

<%= simple_form_for @entry, url: [@entry_scope, @entry] do |form| %>
  <%= form.input :summary %>
  <%= form.input :week, min_max: :lookup %>
  <%= form.input :day, collection: Entry.day_names %>
  <%= form.input :discipline_name, label: 'Discipline', collection: Tag::DISCIPLINES %>
  <%= form.input :zone_name, label: 'Zone', collection: Tag::ZONES.map { |t| [t.titleize,t] } %>
  <%= form.input :period_name, label: 'Period', collection: Tag::PERIODS.map { |t| [t.titleize,t] } %>
  <%= form.input :ability_names, label: 'Abilities',
    collection: Tag::ABILITIES.map { |t| [t.titleize,t]},
    input_html: { multiple: true, style: 'height:6rem' } %>
  <%= form.input :strength_ability_names, label: 'Abilities',
    collection: Tag::STRENGTH_ABILITIES.map { |t| [t.titleize,t]},
    input_html: { multiple: true, style: 'height:6rem' } %>
  <%= form.input :distance, label: 'Distance' %>
  <%= form.input :duration, label: 'Duration' %>
  <%= form.input :notes %>

  <%= form.submit 'Go', class: 'button' %>
<% end %>

app/views/entries/_requirements.html.erb
<span data-role="duration"><i class="fa fa-clock-o"></i> <%= entry.duration_for_unit('min') %></span>
<span> | </span>
<span data-role="distance"><i class="fa fa-road"></i> <%= entry.distance_for_discipline %></span>

app/views/entries/edit.html.erb
<%= render 'form' %>

app/views/entries/index.html.erb
<h1><%= @title %></h1>

<p>
  <% if @training_plan %>
    <%= link_to "Add workout", new_training_plan_entry_path(@training_plan, index_params), class: "button round small" %>
  <% elsif @schedule %>
    <%= link_to "View training plan", training_plan_path(@schedule.training_plan) %>
  <% end %>
</p>

<div class="entries">
  <% if @entries.any? %>
    <%= render @entries, week: @week %>
  <% else %>
    <p>No workouts scheduled for this time period</p>
  <% end %>
</div>

app/views/entries/new.html.erb
<h1>Plan a Workout</h1>

<p>Training Plan: <%= @training_plan.title %></p>

<%= simple_form_for @entry, url: [@training_plan, @entry] do |form| %>
  <%= form.input :week, min_max: :lookup %>
  <%= form.input :day, collection: Entry.day_names %>
  <%= form.input :discipline_name, label: 'Discipline' %>
  <%= form.input :distance_unit, label: 'Distance' %>
  <%= form.input :duration_unit, label: 'Duration' %>
  <%= form.input :summary %>
  <%= form.input :notes %>

  <%= form.submit 'Go', class: 'button' %>
<% end %>

app/views/entries/show.html.erb
<div class="entry">
  <h2><%= @entry.display_day %> <small><%= @entry.display_week %></small></h2>

  <p data-role="summary"><strong><%= @entry.summary %></strong></p>
  <p data-role="requirements"><%= render 'requirements', entry: @entry %></p>
  <p data-role="notes">Notes:<br/>
    <%= @entry.duration %><br/>
    <%= @entry.notes %>
  </p>
  <p data-role="categories"><%= render 'categories', entry: @entry %> </p>

  <p>
    <%= link_to @entry.schedulable_type.humanize, @entry.schedulable %>
    <span> | </span>
    <%= link_to "Edit workout", [:edit, @entry.schedulable, @entry] %>
  </p>
</div>