config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  get "dashboard", to: 'dashboard#show', as: :dashboard, constraints: Routes::LoggedInConstraint.new

  concern :calendar do
    get 'week/:week', to: 'entries#index', as: :week
    get 'week/:week/day/:day', to: 'entries#index', as: :week_day
  end

  resources :schedules, concerns: :calendar do
    resources :entries, path: 'workouts'
  end

  resources :training_plans, concerns: :calendar, path: 'training-plans' do
    resources :entries, path: 'workouts'
  end

  resources :events

  resources :tags

  get 'accounts/start', to: redirect('start')

  devise_for :users,
    skip: [:sessions],
    path: 'accounts',
    path_names: { sign_up: 'start' },
    controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  as :user do
    get 'resume' => 'devise/sessions#new', :as => :new_user_session
    post 'resume' => 'devise/sessions#create', :as => :user_session
    match 'pause' => 'devise/sessions#destroy', :as => :destroy_user_session,
      :via => Devise.mappings[:user].sign_out_via

    get 'start' => 'devise/registrations#new', :as => :sign_up
  end

end

app/models/schedule.rb
# == Schema Information
#
# Table name: schedules
#
#  id               :integer          not null, primary key
#  title            :string(255)
#  training_plan_id :integer
#  event_id         :integer
#  owner_id         :integer
#  peaks_on         :date
#  starts_on        :date
#  ends_on          :date
#  created_at       :datetime
#  updated_at       :datetime
#

class Schedule < ActiveRecord::Base
  belongs_to :training_plan
  belongs_to :event
  belongs_to :owner, class_name: 'User'

  before_create :set_title
  before_save :set_dates
  after_save :set_entry_dates, if: :should_set_entry_dates?

  has_many :entries, as: :schedulable, dependent: :destroy

  scope :active, -> { where("ends_on >= ?", Date.today) }

  # def duration
  # def peak_week
  # def total_weeks
  # def period
  delegate :peak_week, :duration, :total_weeks, :period, to: :training_plan, allow_nil: true

  def weeks
    training_plan.weeks_following(starts_on)
  end

  def week_number(number)
    weeks[number.to_i-1]
  end

  def training_plan
    super || NullTrainingPlan.instance
  end

  private

  def set_title
    return if self.title
    return unless self.event_id_changed?

    self.title = "Training for #{event.title}"
  end

  def set_dates
    set_peaks_on
    set_starts_and_ends_on
  end

  def set_peaks_on
    return unless event_id_changed?

    self.peaks_on = event.occurs_on
  end

  def set_starts_and_ends_on
    return unless self.peaks_on && training_plan_id_changed?

    self.starts_on = training_plan.starts_on(self.peaks_on)
    self.ends_on = training_plan.ends_on(self.peaks_on)
  end

  def set_entry_dates
    raise "Cannot set entry dates without schedule start date" unless self.starts_on

    self.entries = []
    self.training_plan.entries.each do |entry|
      occurs_on = entry.date_relative_to(self.starts_on)
      self.entries.create(entry.copyable_attributes.merge(occurs_on: occurs_on))
    end
  end

  def should_set_entry_dates?
    self.starts_on_changed? && self.training_plan.exists?
  end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  before_action :authenticate_user!

  respond_to :html

  def show
    @schedule = schedule_scope.find(params[:id])
  end

  def new
    @schedule = schedule_scope.build
  end

  def create
    @schedule = schedule_scope.build do |s|
      s.event = scheduled_event
      s.training_plan = scheduled_training_plan
    end

    if @schedule.save
      redirect_to @schedule, notice: "Success!"
    else
      render :new
    end
  end

  private

  def schedule_scope
    current_user.schedules
  end

  def schedule_params
    params.require(:schedule).permit(:event_id, :training_plan_id)
  end

  def scheduled_event
    Event.find(schedule_params[:event_id])
  end

  def scheduled_training_plan
    TrainingPlan.find(schedule_params[:training_plan_id])
  end
end

app/views/schedules/new.html.erb
<h1>Set up your schedule</h1>

<%= simple_form_for @schedule do |form| %>
  <%= form.input :event_id, label: "What are you training for?" do %>
    <%= form.select :event_id,
      Event.order(occurs_on: :asc).map { |r| [r.title, r.id, { class: r.id }] },
      include_blank: true %>
  <% end %>

  <%= form.input :training_plan_id, label: "Choose a training plan" do %>
    <%= form.select :training_plan_id,
      TrainingPlan.order(title: :asc).map { |r| [r.title, r.id, { class: r.id }] },
      include_blank: true %>
  <% end %>

  <%= form.submit 'Go', class: "button btn success" %>
<% end %>

app/views/schedules/show.html.erb
<h1>Schedule</h1>
<h2><%= @schedule.title %></h2>

<p>Training plan <%= link_to @schedule.training_plan.title, @schedule.training_plan %></p>
<p>Starts on <%= l @schedule.starts_on, format: :short %></p>
<p>Peaks on <%= l @schedule.peaks_on, format: :short %></p>
<p>Ends on <%= l @schedule.ends_on, format: :short %></p>

<h5>Overview</h5>
<section class="<%= dom_class(@schedule) %>">
  <% @schedule.weeks.each do |week| %>
    <div class="<%= dom_id(week) %>">
      <%= link_to "#{week.title} : #{l week.starts_on, format: :short}", schedule_week_path(@schedule, week) %>
      <% if week.number == @schedule.peak_week %>
        <p>Race week - <%= @schedule.event.title %></p>
      <% end %>
    </div>
  <% end %>
</section>