config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  get "dashboard", to: 'dashboard#show', as: :dashboard, constraints: Routes::LoggedInConstraint.new

  concern :calendar do
    get 'week/:week', to: 'entries#index', as: :week
    get 'week/:week/day/:day', to: 'entries#index', as: :week_day
  end

  resources :schedules, concerns: :calendar do
    resources :entries, path: 'workouts'
  end

  resources :training_plans, concerns: :calendar, path: 'training-plans' do
    resources :entries, path: 'workouts'
  end

  resources :events

  resources :tags

  get 'accounts/start', to: redirect('start')

  devise_for :users,
    skip: [:sessions],
    path: 'accounts',
    path_names: { sign_up: 'start' },
    controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  as :user do
    get 'resume' => 'devise/sessions#new', :as => :new_user_session
    post 'resume' => 'devise/sessions#create', :as => :user_session
    match 'pause' => 'devise/sessions#destroy', :as => :destroy_user_session,
      :via => Devise.mappings[:user].sign_out_via

    get 'start' => 'devise/registrations#new', :as => :sign_up
  end

end

app/models/training_plan.rb
# == Schema Information
#
# Table name: training_plans
#
#  id          :integer          not null, primary key
#  title       :string(255)      not null
#  summary     :string(255)
#  creator_id  :integer          not null
#  created_at  :datetime
#  updated_at  :datetime
#  total_weeks :integer
#  peak_week   :integer
#

class TrainingPlan < ActiveRecord::Base
  include Concerns::Categorizable

  has_one_category :distance

  belongs_to :creator, class_name: 'User'

  has_many :entries, as: :schedulable, dependent: :destroy

  attachment :thumbnail

  def total_weeks
    read_attribute(:total_weeks) || 27
  end

  def peak_week
    read_attribute(:peak_week) || total_weeks
  end

  def duration
    1..total_weeks
  end

  def weeks
    weeks_following(nil)
  end

  def weeks_following(start_date)
    TrainingWeek.following(start_date, total_weeks) do |w, i|
      number = i + 1
      w.number = number
      w.period = periodization.period(number)
    end
  end

  def week_number(number)
    weeks[number.to_i-1]
  end

  def period(week_number)
    periodization.period(week_number)
  end

  def starts_on(peaks_on)
    peaks_on + 1.day - peak_week.weeks
  end

  def ends_on(peaks_on)
    peaks_on + (total_weeks - peak_week).weeks
  end

  def exists?
    persisted?
  end

  def periodization
    @periodization ||= Periodization::Friel.new(peak_week: peak_week)
  end

end

app/controllers/training_plans_controller.rb
class TrainingPlansController < ApplicationController

  respond_to :html

  def new
    @training_plan = TrainingPlan.new
  end

  def create
    @training_plan = TrainingPlan.new(training_plan_params) do |tp|
      tp.creator = current_user
    end

    if @training_plan.save
      redirect_to @training_plan, notice: "Success!"
    else
      render :new
    end
  end

  def show
    @training_plan = TrainingPlan.find(params[:id])
  end

  def index
    @training_plans = TrainingPlan.all
  end

  def edit
    @training_plan = TrainingPlan.find(params[:id])
  end

  def update
    @training_plan = TrainingPlan.find(params[:id])
    @training_plan.attributes = training_plan_params

    if @training_plan.save
      redirect_to @training_plan, notice: "Success!"
    else
      render :edit
    end
  end

  private

  def training_plan_params
    params.require(:training_plan).permit(:title, :summary, :thumbnail, :distance_name)
  end
end

app/views/training_plans/_form.html.erb
<%= simple_form_for @training_plan do |form| %>
  <%= form.input :distance_name, label: 'Distance' %>
  <%= form.input :title %>
  <%= form.input :summary %>
  <%= form.attachment_field :thumbnail %>
  <%= form.submit 'Go', class: 'button' %>
<% end %>

app/views/training_plans/edit.html.erb
<h1>Update training plan</h1>

<%= render 'form' %>

app/views/training_plans/index.html.erb
<h1>Training Plans</h1>

<% @training_plans.each do |training_plan| %>
  <section>
    <%= link_to training_plan.title, training_plan %>
  </section>
<% end %>

app/views/training_plans/new.html.erb
<h1>Build a training plan</h1>

<%= render 'form' %>

app/views/training_plans/show.html.erb
<h1>Training Plan: <%= @training_plan.title %></h1>

<p><%= @training_plan.summary %></p>

<p><%= image_tag attachment_url(@training_plan, :thumbnail, :fill, 300, 300, filename: 'thumbnail.jpg') %></p>

<%= link_to 'Add workout', new_training_plan_entry_path(@training_plan), class: 'button round small' %>

<h5>Overview</h5>
<section class="<%= dom_class(@training_plan) %>">
<% @training_plan.weeks.each do |week| %>
  <div><%= link_to week.title, training_plan_week_path(@training_plan, week) %></div>
<% end %>
</section>